### ISSUE TITLE
import error

### ISSUE THREAD

**Issue by jeanrjc** [rasbt/watermark#13]
Hi,

After successful install with `pip install watermark` I have an import error with `%load_ext watermark`: 
    `ImportError: No module named watermark`

I can get rid of the error after modifying the `__init__.py`. Changing this:

```
from watermark.watermark import *
```

into

```
from watermark import *
```

make it work. 

Is there a problem with my install or with the `__init__.py` file ?

**Comment by rasbt** [comment]
Thanks for the note, and sorry about the trouble. I will look into it! Quick question, are you using Python 2.x? I think we didn't check for Python 2.x when we replaced the old %install_ext convention and converted watermark into a regular python package a few weeks ago. I should add some continuous integration checks to avoid this problem in future!

**Comment by rasbt** [comment]
Alright, there was definitely an issue with importing it when using Python 2.x. I should be fixed now in v. 1.3.1 :)

**Comment by jeanrjc** [comment]
Yes I have Python 2.7. Thanks !

**Comment by robmarkcole** [comment]
Am seeing this issue with python 3.5 and version 1.4.0 installed via conda on Windows 7

**Comment by rasbt** [comment]
How did you install watermark, via

    pip install watermark 

?

**Comment by robmarkcole** [comment]
https://anaconda.org/conda-forge/watermark

`conda install -c conda-forge watermark `

**Comment by rasbt** [comment]
Hm, that's weird, because it passed the CI tests (incl the CircleCI for Windows) for 1.4.0 in the watermark-feedstock. I will update it and see if there are any issues with 1.5.0 that could help with debugging this issue

**Comment by rasbt** [comment]
We updated the version to 1.5 yesterday (https://github.com/conda-forge/watermark-feedstock/pull/6). Currently, it does not seem to be up in Anaconda Cloud yet but hopefully it will be available shortly and solves the issue. 

PS: Alternatively, I was thinking you may have an older version in your Python path that was causing this issue. Maybe try to uninstall all watermark instances or so.

**Comment by a19grey** [comment]
I had an issue where "import imwatermark" did not work (no module found) but then "import imWatermark" with capital W at least gave a new error "cannot import" 

<img width="1151" alt="image" src="https://user-images.githubusercontent.com/9624002/188300593-95ecfc5b-56b3-4e50-8b1f-ed449f7198a3.png">

**Comment by a19grey** [comment]
Realized I should post my python version. Also I'm in a virtual environment could that be related?

<img width="667" alt="image" src="https://user-images.githubusercontent.com/9624002/188300620-92e50656-ab1d-4473-979f-9ef7404b9211.png">

**Comment by rasbt** [comment]
`imWatermark` is maybe something different. For this package here, you import it as

    from watermark import watermark

**Comment by a19grey** [comment]
Thanks! Yes seems to be a few similar watermarks and i googled my way to the wrong one. Happy coding!

for Science,
-Alex Krause
C: 405-464-2483
