### ISSUE TITLE
Cannot retrieve the version information of OpenCV

### ISSUE THREAD

**Issue by mirjalil** [rasbt/watermark#24]
I can import cv2 package in my jupyter notebook, but watermark cannot find the proper information for this package:

`DistributionNotFound: The 'cv2' distribution was not found and is required by the application`

**Comment by rasbt** [comment]
Hey, Vahid,

hm, that's weird. Can you import the 'cv2' package in your current jupyter session via 
`__import__('cv2')` ?

**Comment by mirjalil** [comment]
Sebastian,

Yes, importing via this command works in jupyter notebook:

```
__import__('cv2')
<module 'cv2' from '/home/vahid/.virtualenvs/cv/lib/python3.4/site-packages/cv2.so'>
```

**Comment by rasbt** [comment]
Hm, what watermark version are you using then? If you are using a version < `v. 1.3.2`  you may have to use the install name ("opencv") instead of the import package name.

**Comment by mirjalil** [comment]
Something is not right. I successfully installed the latest version (1.3.4) 

```Installing collected packages: watermark
  Found existing installation: watermark 1.3.4
    Uninstalling watermark-1.3.4:
      Successfully uninstalled watermark-1.3.4
  Running setup.py develop for watermark
Successfully installed watermark
```

but in jupyter I still get the old version:

```
import watermark
%watermark -w
watermark v. 1.2.3
```

**Comment by rasbt** [comment]
Hm, this sounds more like a general issue related to where/how you installed packages -- maybe sth related to your virtual environments? Maybe you installed a second version of the package in an env, and your jupyter comes from another environment? Maybe just upgrade the package just from Jupyter notebook directly like 

    %%sh pip install watermark --upgrade

**Comment by rasbt** [comment]
PS: it looks like you ran `python setup.py develop`? This does not install the package but it will create an .egg-link in the deployment directory back to the project source code directory.

**Comment by mirjalil** [comment]
Now it seems that the problem is resolved, and `%watermark -v -p cv2` gives the OpenCV version.

I had tried `pip install watermark --upgrade ` as well, but for some reasons, it was not working.

**Comment by rasbt** [comment]
Hm, I suspect there was something weird about the virtual env that you upgraded and the virtual env that loaded the notebook. However, I am glad that it's sorted out now :)
