### ISSUE TITLE
Fails to capture versioning info for missingno package

### ISSUE THREAD

**Issue by AllanLRH** [rasbt/watermark#27]
This plugin fails to capture the version info for the [missingno](https://github.com/ResidentMario/missingno)-package.

Otherwise a really useful little plugin :)

**Comment by rasbt** [comment]
Thanks for the info.
Hm, it appears that `missingno` does not have a proper `__version__` attribute, which seems to be the culprit

![screen shot 2017-02-14 at 10 58 48 am](https://cloud.githubusercontent.com/assets/5618407/22936880/ca82c004-f2a4-11e6-8630-322fa9cfebed.png)

**Comment by ResidentMario** [comment]
Thanks for staying on top of this @AllanLRH, and sorry for the clumsiness. Should be fixed now in the `0.3.4` release.

**Comment by rasbt** [comment]
No worries, and thanks a lot for the quick fix!
