### ISSUE TITLE
Would love the option to get the GPU and Nvidia revision info

### ISSUE THREAD

**Issue by dartdog** [rasbt/watermark#31]
As getting the GPU and Nvidia revisions can be kind of problematic..
Appreciate this great addition to the toolbox..

**Comment by rasbt** [comment]
That's a good suggestion! A parameter like `--gpu_info` could be a nice addition. I am wondering though how to do this in a general way (e.g., some way that works across OS's and would also work with ATI cards).

For Nvidia cards, for example, the best way would probably be to use

    !cat nvidia-smi

or 

    !cat /proc/driver/nvidia/gpus/0/information

In IPython/Jupyter Notebook

I will leave this issue open and hope someone has a good idea how to do this elegantly within watermark :)

**Comment by dartdog** [comment]
Yeh but I don't know of anyone using amd for mach learning? but appreciate the !command info! that is fine for now, I should know but,,. heck

**Comment by 907Resident** [comment]
Not sure if this is still of interest, but I took a stab at adding an argument that would at least work for NVIDIA-based GPUs. Details in #90 will share more insight on what could be expected if merged.

**Comment by d-kleine** [comment]
seems to be fixed, right?

**Comment by rasbt** [comment]
yup :)
