### ISSUE TITLE
Is it possible to add the git branch to the report?

### ISSUE THREAD

**Issue by ianozsvald** [rasbt/watermark#36]
Currently we can add the git hash, is it possible to show the git branch as well? This is more interpretable than the hash.

`git rev-parse --abbrev-ref HEAD` seems to do it at the command line as noted (with other options) here: https://stackoverflow.com/questions/6245570/how-to-get-the-current-branch-name-in-git

Sidenote - I've introduced `watermark` to many colleagues, I tend to make sure it is adopted by projects in each organisation I work with, many thanks for supporting it!

**Comment by rasbt** [comment]
Thanks for the comment, and I am happy to hear that you find the watermark extension useful :). I think adding an option for the git branch sounds like a good idea, I can certainly add sth like that (i.e., a `--gitbranch` flag).

**Comment by rasbt** [comment]
just pushed a PR (#37) to implemented the suggested option. Seems to work okay for me, but it would be nice if you could check it out and give some short feedback before I push a new watermark version to PyPI and conda-forge

**Comment by rasbt** [comment]
addressed in #37
