### ISSUE TITLE
Watermark doesn't catch classes/functions imported using `from`

### ISSUE THREAD

**Issue by matrs** [rasbt/watermark#44]
Hello,
first, thank you for this package. 
I just noticed this behaviour when importing a subclass from `Biopython`:

```python 
from Bio import SeqIO
``` 
 

the `watermark` magic doesn't show the info of the imported package (`Bio`). I'm aware that I can solve this doing 
```python
import Bio
```
but i was wondering if it could be implemented given that for many libraries It is customary to use: 
```python
from X import Y
```

Cheers!

**Comment by rasbt** [comment]
Hi there,

could you show your usage example? I am wondering because there is currently no feature to print all the imported packages automatically (we may add that at some point though, as mentioned in #5)

So in order to show the package version, you would execute

    %watermark -p Bio

**Comment by matrs** [comment]
Sorry, I wasn't clear enough.
I'm using `%watermark -iv`  to print the version of all imported modules.
So when I use
```python 
from Bio import SeqIO
``` 
`%watermark -iv` doesn't print any information about the module `Bio`,  as if It wasn't exported. Of course, it works if I use
  ```python
import Bio
```
I was expecting that  `%watermark -iv` printed information about `Bio` despite the way I imported it because the `Bio` module it's actually being imported in both cases. So this is a particular example of the general case where any submodule/class/function is imported using 
```python
from X import Y
```
and `%watermark -iv` doesn't print any information for `X` (or `Y` if you prefer that).

Why I'm expecting this behavior? because I'm using this package to get all the information about the packages used in a notebook and maybe that isn't the use case intended for `watermark`.

**Comment by rasbt** [comment]
Oh sorry, I was confused and forgot that we already added the `-iv` flag ... for some reason, I thought this was still work in progress.

I agree with you that it would be super nice to support the `from X import Y` scenarios. And I think this is an easy fix. I think I can just implement it right-away in a few minutes

**Comment by rasbt** [comment]
That functionality should work in the the new 1.8.0 version now :)

**Comment by matrs** [comment]
Thank you , that was fast!
