### ISSUE TITLE
`-d` doesn't print date, only when combined with `-u`

### ISSUE THREAD

**Issue by rasbt** [rasbt/watermark#76]
There is currently an issue that `-d` alone doesn't print the date. It only works with `-u`. In my opinion `-d` should work as a standalone argument.

![Screen Shot 2021-02-23 at 10 03 24 PM](https://user-images.githubusercontent.com/5618407/108945878-08e39e80-7623-11eb-856a-124edb0f8905.png)

**Comment by npneeraj** [comment]
Maybe, some middleware is blocking your intentions. Please refer the official python docs: [time-date in python](https://docs.python.org/3/library/datetime.html)
