### ISSUE TITLE
Watermark fails to identify (some) packages when imported as 'from X import Y'

### ISSUE THREAD

**Issue by adrien-perello** [rasbt/watermark#77]
See the jupyter notebook outputs below: 

![Screenshot from 2021-04-09 12-46-50](https://user-images.githubusercontent.com/76055749/114169709-33b75700-9932-11eb-88be-5c8aca104fea.png)

**Comment by rasbt** [comment]
Oh yeah, this looks like a bug. Not sure what is different about sympy that causes this to happen. Have to look into this.

**Comment by adrien-perello** [comment]
It seems like watermark is not the only one to fail at detecting the sympy module when doing `from X import Y`. Could it be that the problem comes from the sympy module itself?

![Firefox_Screenshot_2021-04-12T08-06-54 553Z](https://user-images.githubusercontent.com/76055749/114362436-9cdbdc00-9b77-11eb-9c63-da57648d91fe.png)

**Comment by rasbt** [comment]
Thanks for looking into this. Yeah, it looks weird, and I don't know why sympy only shows up in the list of imports of it is imported directly. Taking a quick look at the package structure at https://github.com/sympy/sympy/tree/master/sympy, it looks like it uses the regular package conventions with having `__init__.py` files in the submodules. Or, in other words, based on my brief look, it doesn't look like that SymPy uses some custom hacks for imports

**Comment by koaning** [comment]
It seems like scikit-learn also has this issue. 

![image](https://user-images.githubusercontent.com/1019791/122515963-766e6d00-d00e-11eb-84ba-df20ac6a406a.png)

**Comment by rasbt** [comment]
Thanks. I am not sure how to resolve this / if this can be resolved. I am hoping someone might know a solution

**Comment by jankaWIS** [comment]
The same issue goes also for the `lmfit` package, it works when loading the entire package, exactly as described above. The other packages are loaded as checks, notice that for `scipy` there is no such problem. I'm using the latest version of watermark [v. 2.3.0 (January 3, 2022)](https://github.com/rasbt/watermark#v-230-january-3-2022).

![image](https://user-images.githubusercontent.com/54404810/157640987-44f43313-40db-467d-a153-ff6610a698a4.png)

**Comment by rasbt** [comment]
Thanks for the note. I wish I knew a good way to fix that :(

**Comment by delip** [comment]
joining the chorus here, as I noticed `pytorch_lightning` package having the same issue:

```
import watermark
from pytorch_lightning import seed_everything

if __name__ == '__main__':
    seed_everything(42)
    print(watermark.watermark(machine=True, globals_=globals(), iversions=True, python=True))
```

**Comment by rasbt** [comment]
Thanks for posting. Still don’t know a good solution for this 😢

**Comment by fomightez** [comment]
Another couple brought me here:

```python
from statistics import mean, median, mode, StatisticsError
from halo import HaloNotebook as Halo
```

But yet `from sklearn import metrics` in [the demo](https://nbviewer.org/github/rasbt/watermark/blob/master/docs/watermark.ipynb) works despite [koaning's example]https://github.com/rasbt/watermark/issues/77#issuecomment-863789430)  with `sklearn.linear_model`.

**Comment by d-kleine** [comment]
> Still don’t know a good solution for this 😢

I did something similar some time ago: I have extracted the imported modules in the code cells in a jupyter notebook with [regular expressions](https://stackoverflow.com/questions/53632274/regex-to-capture-all-import-statements), but I don't know if this a good solution for that issue.

**Comment by rasbt** [comment]
Thanks for sharing though! Hm yeah, I feel like there must be a direct way in Python somehow ...

**Comment by d-kleine** [comment]
I think the issue from the import command `from module_name import function_name` is not covert by `watermark_self.shell.user_ns` or `globals_`. I have tested this for the following import statements:

```python
from sklearn.metrics import accuracy_score # as ...
from pandas import DataFrame # as ...
import re # as ...
from os import path # as ...
import scipy.cluster # as ...
```

and took a closer into the output of `ns` in `watermark.py`:

```python
...
if args['iversions']:
            if watermark_self:
                ns = watermark_self.shell.user_ns
            elif globals_:
                ns = globals_
            else:
                raise RuntimeError(
                    "Either `watermark_self` or `globals_` must be provided "
                    "to show imported package versions."
                )
            print(ns) # CHANGE: PRINT OUTPUT
            output.append(_get_all_import_versions(ns))
...
```

When taking a look into the output of ns, from my point of view, there is no way to extract the module name directly for the import command `from module_name import function_name` because this seem to only import the function (`<function ...`), but not the underlying module (`<module ...`), see the case for _accuracy_score_ from _sklearn_. But if you import a submodule from a module like `from module_name import submodule_name` or `import  module_name.submodule_name`, the module will be in the output (`<module ...`), see scipy. So, in conclusion, it does not work when importing a **function**, but it works when importing a **submodule** of a module.

I have played around a little with the code in watermark.py and changed following things:

1. Added regular expressions import

```python
import re
```

2. Updated `_get_all_import_versions(vars)` function with module import expressions

```python
def _get_all_import_versions(vars):
    to_print = {}
    imported_pkgs = {
        val.__name__.split(".")[0]
        for val in list(vars.values())
        if isinstance(val, types.ModuleType)
    }

    ### CHANGES START
    import_pattern = re.compile(r"import\s+([\w\.]+)")
    from_pattern = re.compile(r"from\s+([\w\.]+)\s+import")

    for code in vars["_ih"]:
        import_matches = import_pattern.findall(code)
        from_matches = from_pattern.findall(code)

        
        if import_matches:
            for match in import_matches:
                imported_pkgs.add(match.split(".")[0])
                
        if from_matches:
            for match in from_matches:
                imported_pkgs.add(match.split(".")[0])
    ### CHANGES END    

    imported_pkgs.discard("builtins")

    for pkg_name in imported_pkgs:
        pkg_version = _get_package_version(pkg_name)
        if pkg_version not in ("not installed", "unknown"):
            to_print[pkg_name] = pkg_version
    return to_print
```

This is just a showcase, and I still don't know why `os` is not in the output (same without the changes). What do you think?

**Comment by martinp7** [comment]
I just had similar issue and from what I understand we always have the problem when we import a function or a class directly e.g.

```python
from scipy import special
from sklearn.linear_model import LinearRegression
```

The main problem is that `_get_all_import_versions` keeps only the module objects. However, when importing a function or a class it does not create a variable of type `types.ModuleType`.

To fix the issue, we could retrieve from `vars`:
1. module objects created by imports (as already done)
2. modules objects associated to the classes/functions imported

Here are the suggested changes:
```python
import inspect


def _get_all_import_versions(vars):
    to_print = {}

    # Retrieve all the modules imported directly e.g. from sklearn import metrics, import pandas
    imported_modules = {
        val
        for val in list(globals().values())
        if isinstance(val, types.ModuleType)
    }

    # Add all the modules imported during import of functions or classes e.g. from sklearn.linear_model import LinearRegression
    imported_modules.update(
        {
            inspect.getmodule(val) for val in list(globals().values()) if inspect.isclass(val) or inspect.isfunction(val)
        }
    )

    imported_pkgs = {module.__name__.split(".")[0] for module in imported_modules}
    
    imported_pkgs.discard("builtins")
    for pkg_name in imported_pkgs:
        pkg_version = _get_package_version(pkg_name)
        if pkg_version not in ("not installed", "unknown"):
            to_print[pkg_name] = pkg_version

    return to_print
```

--------


Here is a quick example:
```python
from sympy import poly, solve
import numpy as np
from sklearn.linear_model import LinearRegression
import pandas


def _get_all_import_versions(vars):
    ### To be removed, I put it here to avoid to pollute the globals with non relevant imports
    import inspect
    import types
    from watermark.watermark import _get_package_version
    ###
    
    to_print = {}

    # Retrieve all the modules imported directly e.g. from sklearn import metrics, import pandas
    imported_modules = {
        val
        for val in list(vars.values())
        if isinstance(val, types.ModuleType)
    }

    # Add all the modules imported during import of function or class e.g. from sklearn.linear_model import LinearRegression
    imported_modules.update(
        {
            inspect.getmodule(val) for val in list(vars.values()) if inspect.isclass(val) or inspect.isfunction(val)
        }
    )

    imported_pkgs = {module.__name__.split(".")[0] for module in imported_modules}
    
    imported_pkgs.discard("builtins")
    for pkg_name in imported_pkgs:
        pkg_version = _get_package_version(pkg_name)
        if pkg_version not in ("not installed", "unknown"):
            to_print[pkg_name] = pkg_version

    return to_print

_get_all_import_versions(globals())
# {'sympy': '1.12.1', 'pandas': '2.2.2', 'numpy': '1.26.4', 'sklearn': '1.5.1'}
```

What do you think of this solution?

**Comment by rasbt** [comment]
This is looks like a nice workaround, thanks! Would you have time to add this as a PR some time? That'd be awesome! Otherwise, let me know, I can help with this.

**Comment by d-kleine** [comment]
Just tested directly in watermark wiht `%watermark -iv`, lgtm 👍🏻
