### ISSUE TITLE
%install_ext is deprecated...

### ISSUE THREAD

**Issue by janschulz** [rasbt/watermark#8]
IPython deprecated the `%install_ext` magic (https://github.com/ipython/ipython/issues/8634). The replacement story is using a package to distribute the extension and then use `%load_ext package.extension` to load the extension.

Ah, and shamless plug: if you don't want to work with your own package, there is also now https://github.com/ipython-contrib/IPython-extensions watermark would be a great addition there!

**Comment by rasbt** [comment]
Thanks for the heads up, Jan, the change makes sense to me; I think extensions will be a tad easier to maintain this way. @bollwyvl submitted a very nice pull request a while ago with a "write metadata" option (#7). There were just a few changes to be made, but after it's merged, I will go ahead and turn `watermark` into a package/module. 

About the link: Thanks for that, it's also a nice idea to bundle extension in a package.
