### ISSUE TITLE
Remove Travis CI config and replace build status badge with AppVeyor?

### ISSUE THREAD

**Issue by mbrukman** [rasbt/watermark#84]
Travis CI no longer works for open-source projects, and I see recent PRs in this repo are being tested via AppVeyor, but the main `README.md` still lists a Travis CI badge that links to an inactive project, and there's still a `.travis.yml` config that can be removed.

https://www.appveyor.com/docs/status-badges/ has documentation for how to create an AppVeyor badge; I think you can use this URL for the image badge:

* https://ci.appveyor.com/api/projects/status/github/rasbt/watermark?svg=true

Which looks like this: ![AppVeyor badge](https://ci.appveyor.com/api/projects/status/github/rasbt/watermark?svg=true), but I don't know what the URL to your project is, only you do.

**Comment by rasbt** [comment]
Thanks, good call, totally forgot to update this. Should be fixed now!

**Comment by mbrukman** [comment]
The badge was updated in https://github.com/rasbt/watermark/commit/01898e01324210c30f557600993568dbcf12d3af but the `.travis.yml` file is still there. I'll send a PR to clean this up.
