### ISSUE TITLE
Why not use an ISO-8601 date format?

### ISSUE THREAD

**Issue by ianozsvald** [rasbt/watermark#9]
Hi there. Out of curiosity - how come you're not using an ISO-8601 date format (e.g. 2015-01-02 where this is unambiguously the 2nd of Jan 2015 and cannot be the 1st of Feb)? Would you accept a PR to switch to ISO-8601?

**Comment by rasbt** [comment]
Sounds like a good idea, I am actually using this format everywhere but here (for whatever reason). A PR would be very welcome!

**Comment by ianozsvald** [comment]
So one totally quick hack is to replace your existing default `strftime` with an ISO-8601 alternative:
```
        if not any(vars(args).values()):
            self.out += strftime("%Y-%m-%dT%H:%M:%S")
            #self.out += strftime('%m/%d/%Y %H:%M:%S')
```
and then by way of a very quick test I get:
```
$ python -c "import watermark; watermark.WaterMark().watermark('')"
2016-01-29T17:52:54

CPython 3.4.4
IPython 4.0.1

compiler   : GCC 4.4.7 20120313 (Red Hat 4.4.7-1)
system     : Linux
release    : 3.16.0-38-generic
machine    : x86_64
processor  : x86_64
CPU cores  : 8
interpreter: 64bit
```

**Comment by rasbt** [comment]
Looks good to me. Personally, I don't like the "T" in "2016-01-29T17:52:54", but hey, let's just go with the standard here ;). 

I think we could also remove

    @argument('-e', '--eurodate', action='store_true', help='prints current date as DD/MM/YYYY')

then and update

    @argument('-d', '--date', action='store_true', help='prints current date as MM/DD/YYYY')

Are you planning to prepare a pull request?

**Comment by ianozsvald** [comment]
I'll avoid a PR if that's OK, the change is pretty minor. I hope that's OK?
I.

**Comment by rasbt** [comment]
Sure, that's absolutely fine! I'll take a look at it :).

**Comment by rasbt** [comment]
I just pushed the update. Thanks again for the suggestion!

**Comment by ianozsvald** [comment]
Glad it was a useful question :-)

**Comment by ianozsvald** [comment]
Just to note - I've added a link to my data science notes, cheers! https://github.com/ianozsvald/data_science_delivered

**Comment by rasbt** [comment]
Thanks, Ian. That's a pretty cool outline; it transfers nicely into a project planning todo-checklist ;)
